[package]
name = "hyper-websocket-chat"
version = "0.1.0"
authors = ["ibaryshnikov"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.11.0"
futures-preview = "0.3.0-alpha.19"
hyper = "0.13.0-alpha.4"
tokio = "0.2.0-alpha.6"
tokio-io = "0.2.0-alpha.6"
rust-crypto = "0.2.36"
